imports:
    - { resource: 'fixtures/shop_configuration.yaml' }
    - { resource: 'fixtures/wine_catalog.yaml' }
    - { resource: 'fixtures/wines.yaml' }
    - { resource: 'fixtures/glassware.yaml' }
    - { resource: 'fixtures/experiences.yaml' }
    - { resource: 'fixtures/promotions.yaml' }
    - { resource: 'fixtures/demo_data.yaml' }
    - { resource: "twig_hooks/**/*.yaml" }
