<?php

declare(strict_types=1);

namespace Webgriffe\SyliusFixturesPlugin\Fixture\Factory;

use Faker\Factory;
use Faker\Generator;
use Sylius\Bundle\CoreBundle\Fixture\Factory\OrderExampleFactory as BaseOrderExampleFactory;
use Sylius\Component\Addressing\Model\CountryInterface;
use Sylius\Component\Core\Model\AddressInterface;
use Sylius\Component\Core\Model\ChannelInterface;
use Sylius\Component\Core\Model\OrderInterface;
use Sylius\Component\Core\OrderCheckoutTransitions;
use Sylius\Component\Customer\Model\CustomerInterface;
use Webmozart\Assert\Assert;

/**
 * Creates the demo orders in the default locale of the channel instead of a random one, with addresses
 * localized on their own country instead of the American ones generated by Sylius.
 *
 * Sylius picks a random locale and then loads the products joining only the translation of that
 * locale: reading the product name in any other locale (the one assigned to the entity by the
 * translatable locale assigner) would create an empty translation and break the flush.
 */
final class OrderExampleFactory extends BaseOrderExampleFactory
{
    private const FAKER_LOCALES = [
        'AT' => 'de_AT',
        'BE' => 'nl_BE',
        'BG' => 'bg_BG',
        'CH' => 'de_CH',
        'CY' => 'el_CY',
        'CZ' => 'cs_CZ',
        'DE' => 'de_DE',
        'DK' => 'da_DK',
        'EE' => 'et_EE',
        'ES' => 'es_ES',
        'FI' => 'fi_FI',
        'FR' => 'fr_FR',
        'GB' => 'en_GB',
        'GR' => 'el_GR',
        'HR' => 'hr_HR',
        'HU' => 'hu_HU',
        'IE' => 'en_GB',
        'IT' => 'it_IT',
        'LT' => 'lt_LT',
        'LU' => 'fr_FR',
        'LV' => 'lv_LV',
        'MT' => 'en_GB',
        'NL' => 'nl_NL',
        'NO' => 'nb_NO',
        'PL' => 'pl_PL',
        'PT' => 'pt_PT',
        'RO' => 'ro_RO',
        'SE' => 'sv_SE',
        'SI' => 'sl_SI',
        'SK' => 'sk_SK',
    ];

    /** @var array<string, Generator> */
    private array $localizedFakers = [];

    #[\Override]
    protected function createOrder(
        ChannelInterface $channel,
        CustomerInterface $customer,
        CountryInterface $country,
        \DateTimeInterface $createdAt,
    ): OrderInterface {
        $defaultLocale = $channel->getDefaultLocale();
        Assert::notNull($defaultLocale, sprintf('The channel "%s" has no default locale.', (string) $channel->getCode()));

        $baseCurrency = $channel->getBaseCurrency();
        Assert::notNull($baseCurrency, sprintf('The channel "%s" has no base currency.', (string) $channel->getCode()));

        /** @var OrderInterface $order */
        $order = $this->orderFactory->createNew();
        $order->setChannel($channel);
        $order->setCustomer($customer);
        $order->setCurrencyCode($baseCurrency->getCode());
        $order->setLocaleCode($defaultLocale->getCode());

        $this->generateItems($order);

        $this->address($order, (string) $country->getCode());
        $this->selectShipping($order, $createdAt);
        $this->selectPayment($order, $createdAt);
        $this->completeCheckout($order);

        return $order;
    }

    #[\Override]
    protected function address(OrderInterface $order, string $countryCode): void
    {
        $faker = $this->localizedFaker($countryCode);

        /** @var AddressInterface $address */
        $address = $this->addressFactory->createNew();
        $address->setFirstName($faker->firstName());
        $address->setLastName($faker->lastName());
        $address->setStreet($faker->streetAddress());
        $address->setCountryCode($countryCode);
        $address->setCity($faker->city());
        $address->setPostcode($faker->postcode());
        $address->setPhoneNumber($faker->phoneNumber());

        $order->setShippingAddress($address);
        $order->setBillingAddress(clone $address);

        $this->applyCheckoutStateTransition($order, OrderCheckoutTransitions::TRANSITION_ADDRESS);
    }

    private function localizedFaker(string $countryCode): Generator
    {
        return $this->localizedFakers[$countryCode] ??= Factory::create(self::FAKER_LOCALES[$countryCode] ?? 'it_IT');
    }
}
