<?php

declare(strict_types=1);

namespace Webgriffe\SyliusFixturesPlugin\Fixture\Factory;

use Faker\Factory;
use Faker\Generator;
use Sylius\Bundle\CoreBundle\Fixture\Factory\OrderExampleFactory as BaseOrderExampleFactory;
use Sylius\Component\Addressing\Model\CountryInterface;
use Sylius\Component\Addressing\Model\ProvinceInterface;
use Sylius\Component\Core\Model\AddressInterface;
use Sylius\Component\Core\Model\ChannelInterface;
use Sylius\Component\Core\Model\OrderInterface;
use Sylius\Component\Core\Model\ShippingMethodInterface;
use Sylius\Component\Core\OrderCheckoutStates;
use Sylius\Component\Core\OrderCheckoutTransitions;
use Sylius\Component\Customer\Model\CustomerInterface;
use Sylius\Component\Order\OrderTransitions;
use Sylius\Component\Shipping\Model\ShipmentInterface;
use Sylius\Component\Shipping\Resolver\ShippingMethodsResolverInterface;
use Webmozart\Assert\Assert;

/**
 * Creates the demo orders in the default locale of the channel instead of a random one, with addresses
 * localized on their own country instead of the American ones generated by Sylius, and cancels them when
 * the fixture asks for it. The shipments that left the warehouse also carry a tracking code, which Sylius
 * never writes.
 *
 * Sylius ships every order with a random method of the channel, ignoring its zone, its categories and its
 * rules: the demo orders are shipped instead with one of the methods the customer could have chosen.
 *
 * Sylius picks a random locale and then loads the products joining only the translation of that
 * locale: reading the product name in any other locale (the one assigned to the entity by the
 * translatable locale assigner) would create an empty translation and break the flush.
 */
final class OrderExampleFactory extends BaseOrderExampleFactory
{
    private const FAKER_LOCALES = [
        'AT' => 'de_AT',
        'BE' => 'nl_BE',
        'BG' => 'bg_BG',
        'CH' => 'de_CH',
        'CY' => 'el_CY',
        'CZ' => 'cs_CZ',
        'DE' => 'de_DE',
        'DK' => 'da_DK',
        'EE' => 'et_EE',
        'ES' => 'es_ES',
        'FI' => 'fi_FI',
        'FR' => 'fr_FR',
        'GB' => 'en_GB',
        'GR' => 'el_GR',
        'HR' => 'hr_HR',
        'HU' => 'hu_HU',
        'IE' => 'en_GB',
        'IT' => 'it_IT',
        'LT' => 'lt_LT',
        'LU' => 'fr_FR',
        'LV' => 'lv_LV',
        'MT' => 'en_GB',
        'NL' => 'nl_NL',
        'NO' => 'nb_NO',
        'PL' => 'pl_PL',
        'PT' => 'pt_PT',
        'RO' => 'ro_RO',
        'SE' => 'sv_SE',
        'SI' => 'sl_SI',
        'SK' => 'sk_SK',
    ];

    /**
     * Regions of the countries the shop ships to, to fill the province name of the addresses. Faker has no
     * reliable data for them: half of the locales have no region at all, and some fall back to the American
     * states, so a Bulgarian address would be delivered to Vermont.
     *
     * @var array<string, list<string>>
     */
    private const REGIONS = [
        'AT' => ['Wien', 'Steiermark', 'Tirol', 'Salzburg'],
        'BE' => ['Antwerpen', 'Oost-Vlaanderen', 'Brabant wallon', 'Liège'],
        'BG' => ['Sofia-grad', 'Plovdiv', 'Varna', 'Burgas'],
        'CH' => ['Zürich', 'Bern', 'Vaud', 'Ticino'],
        'CY' => ['Lefkosía', 'Lemesós', 'Lárnaka'],
        'CZ' => ['Praha', 'Jihomoravský kraj', 'Moravskoslezský kraj'],
        'DE' => ['Bayern', 'Nordrhein-Westfalen', 'Baden-Württemberg', 'Sachsen'],
        'DK' => ['Hovedstaden', 'Midtjylland', 'Syddanmark'],
        'EE' => ['Harjumaa', 'Tartumaa', 'Pärnumaa'],
        'ES' => ['Madrid', 'Cataluña', 'Andalucía', 'País Vasco'],
        'FI' => ['Uusimaa', 'Pirkanmaa', 'Lappi'],
        'FR' => ['Île-de-France', 'Nouvelle-Aquitaine', 'Occitanie', 'Bretagne'],
        'GB' => ['Greater London', 'West Midlands', 'Kent', 'Yorkshire'],
        'GR' => ['Attikí', 'Kentrikí Makedonía', 'Kríti'],
        'HR' => ['Zagrebačka', 'Splitsko-dalmatinska', 'Istarska'],
        'HU' => ['Budapest', 'Pest', 'Győr-Moson-Sopron'],
        'IE' => ['Leinster', 'Munster', 'Connacht'],
        'LT' => ['Vilniaus apskritis', 'Kauno apskritis', 'Klaipėdos apskritis'],
        'LU' => ['Luxembourg', 'Diekirch', 'Grevenmacher'],
        'LV' => ['Rīga', 'Kurzeme', 'Vidzeme'],
        'MT' => ['Malta Xlokk', 'Malta Majjistral', 'Għawdex'],
        'NL' => ['Noord-Holland', 'Zuid-Holland', 'Utrecht', 'Noord-Brabant'],
        'NO' => ['Oslo', 'Vestland', 'Rogaland', 'Trøndelag'],
        'PL' => ['mazowieckie', 'małopolskie', 'dolnośląskie', 'pomorskie'],
        'PT' => ['Lisboa', 'Porto', 'Faro', 'Braga'],
        'RO' => ['București', 'Cluj', 'Timiș', 'Iași'],
        'SE' => ['Stockholms län', 'Västra Götalands län', 'Skåne län'],
        'SI' => ['Osrednjeslovenska', 'Podravska', 'Obalno-kraška'],
        'SK' => ['Bratislavský kraj', 'Košický kraj', 'Žilinský kraj'],
    ];

    /** @var array<string, Generator> */
    private array $localizedFakers = [];

    private ?ShippingMethodsResolverInterface $shippingMethodsResolver = null;

    /** Injected by a setter, so that the arguments of the Sylius factory can be kept as they are. */
    public function setShippingMethodsResolver(ShippingMethodsResolverInterface $shippingMethodsResolver): void
    {
        $this->shippingMethodsResolver = $shippingMethodsResolver;
    }

    /** @param array<string, mixed> $options */
    #[\Override]
    public function create(array $options = []): OrderInterface
    {
        $state = $options['state'] ?? 'completed';
        unset($options['state']);

        $order = parent::create($options);

        if ('cancelled' === $state) {
            $this->stateMachine->apply($order, OrderTransitions::GRAPH, OrderTransitions::TRANSITION_CANCEL);
        }

        $this->trackShipments($order);

        return $order;
    }

    #[\Override]
    protected function selectShipping(OrderInterface $order, \DateTimeInterface $createdAt): void
    {
        if (OrderCheckoutStates::STATE_SHIPPING_SKIPPED === $order->getCheckoutState()) {
            return;
        }

        foreach ($order->getShipments() as $shipment) {
            $shipment->setMethod($this->eligibleShippingMethod($shipment));
            $shipment->setCreatedAt($createdAt);
        }

        $this->applyCheckoutStateTransition($order, OrderCheckoutTransitions::TRANSITION_SELECT_SHIPPING);
    }

    private function eligibleShippingMethod(ShipmentInterface $shipment): ShippingMethodInterface
    {
        Assert::notNull($this->shippingMethodsResolver, 'The shipping methods resolver has not been injected.');

        $shippingMethods = $this->shippingMethodsResolver->getSupportedMethods($shipment);
        Assert::notEmpty($shippingMethods, 'No shipping method is eligible for the shipment of a demo order.');

        $shippingMethod = $this->faker->randomElement($shippingMethods);
        Assert::isInstanceOf($shippingMethod, ShippingMethodInterface::class);

        return $shippingMethod;
    }

    /**
     * A parcel that left the warehouse has a tracking code, so the shipped shipments get a plausible one:
     * two letters of the carrier and eleven digits, the shape used by the express couriers.
     */
    private function trackShipments(OrderInterface $order): void
    {
        foreach ($order->getShipments() as $shipment) {
            if (ShipmentInterface::STATE_SHIPPED !== $shipment->getState()) {
                continue;
            }

            $shipment->setTracking($this->faker->numerify('WG###########'));
        }
    }

    #[\Override]
    protected function createOrder(
        ChannelInterface $channel,
        CustomerInterface $customer,
        CountryInterface $country,
        \DateTimeInterface $createdAt,
    ): OrderInterface {
        $defaultLocale = $channel->getDefaultLocale();
        Assert::notNull($defaultLocale, sprintf('The channel "%s" has no default locale.', (string) $channel->getCode()));

        $baseCurrency = $channel->getBaseCurrency();
        Assert::notNull($baseCurrency, sprintf('The channel "%s" has no base currency.', (string) $channel->getCode()));

        /** @var OrderInterface $order */
        $order = $this->orderFactory->createNew();
        $order->setChannel($channel);
        $order->setCustomer($customer);
        $order->setCurrencyCode($baseCurrency->getCode());
        $order->setLocaleCode($defaultLocale->getCode());

        $this->generateItems($order);

        $this->address($order, (string) $country->getCode());
        $this->selectShipping($order, $createdAt);
        $this->selectPayment($order, $createdAt);
        $this->completeCheckout($order);

        return $order;
    }

    #[\Override]
    protected function address(OrderInterface $order, string $countryCode): void
    {
        $faker = $this->localizedFaker($countryCode);

        /** @var AddressInterface $address */
        $address = $this->addressFactory->createNew();
        $address->setFirstName($faker->firstName());
        $address->setLastName($faker->lastName());
        $address->setStreet($faker->streetAddress());
        $address->setCountryCode($countryCode);
        $address->setCity($faker->city());
        $address->setPostcode($faker->postcode());
        $address->setPhoneNumber($faker->phoneNumber());
        $this->applyProvince($address, $countryCode, $faker);

        $order->setShippingAddress($address);
        $order->setBillingAddress(clone $address);

        $this->applyCheckoutStateTransition($order, OrderCheckoutTransitions::TRANSITION_ADDRESS);
    }

    /**
     * The province code only exists where the country actually has provinces, Italy in the demo store: the
     * other countries get the name of a region as free text, which is what Sylius expects from them.
     */
    private function applyProvince(AddressInterface $address, string $countryCode, Generator $faker): void
    {
        $country = $this->countryRepository->findOneBy(['code' => $countryCode]);

        if ($country instanceof CountryInterface && $country->hasProvinces()) {
            /** @var ProvinceInterface $province */
            $province = $faker->randomElement($country->getProvinces()->toArray());

            $address->setProvinceCode($province->getCode());

            return;
        }

        $regions = self::REGIONS[$countryCode] ?? null;
        if (null === $regions) {
            return;
        }

        $region = $faker->randomElement($regions);
        Assert::string($region);

        $address->setProvinceName($region);
    }

    private function localizedFaker(string $countryCode): Generator
    {
        return $this->localizedFakers[$countryCode] ??= Factory::create(self::FAKER_LOCALES[$countryCode] ?? 'it_IT');
    }
}
